name: Test Suite

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
      working-directory: backend    
      env:
        DOTENV_KEY: ${{ secrets.DOTENV_KEY }}

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
      env:
        DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
      working-directory: backend

    - name: Run Tests
      run: npx hardhat test
      env:
        DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
      working-directory: backend
